# Generated by Django 4.2 on 2023-04-26 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0005_listing_band"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="band",
            name="description",
        ),
        migrations.RemoveField(
            model_name="band",
            name="sold",
        ),
        migrations.RemoveField(
            model_name="band",
            name="type",
        ),
        migrations.RemoveField(
            model_name="band",
            name="year",
        ),
        migrations.AddField(
            model_name="listing",
            name="description",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="sold",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="type",
            field=models.CharField(
                choices=[
                    ("REC", "Records"),
                    ("CLO", "Clothing"),
                    ("POS", "Posters"),
                    ("MIS", "Miscellaneous"),
                ],
                default="MIS",
                max_length=5,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="year",
            field=models.IntegerField(
                default=1900,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2023),
                ],
            ),
            preserve_default=False,
        ),
    ]
