# Generated by Django 4.2 on 2023-05-10 07:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_auto_20230509_0928"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="follows",
            field=models.ManyToManyField(
                limit_choices_to={"role": "CREATOR"},
                to=settings.AUTH_USER_MODEL,
                verbose_name="suit",
            ),
        ),
    ]
