# Generated by Django 4.2 on 2023-05-10 08:42

from django.db import migrations


def author_to_contributors(apps, schema_migration):
    Blog = apps.get_model('blog', 'Blog')
    for blog in Blog.objects.all():
        blog.contributors.add(
            blog.author,
            through_defaults={'contribution': 'Auteur principal'})


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_blog_author_blogcontributor_blog_contributors"),
    ]

    operations = [migrations.RunPython(author_to_contributors)]
