# Generated by Django 4.2 on 2023-05-10 09:15

from django.db import migrations


def author_to_contributors(apps, schema_migration):
    Blog = apps.get_model("blog", "Blog")
    for blog in Blog.objects.all():
        blog.contributors.add(
            blog.author, through_defaults={"contribution": "Auteur principal"}
        )


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_auto_20230510_1042"),
    ]

    operations = [migrations.RunPython(author_to_contributors)]
